"""Маніфест hero-банерів та ключових зображень для sync_site_images."""

from __future__ import annotations

HERO_IMAGES: dict[str, tuple[str, str]] = {
    "tehnichni-pasporty-bti": ("images/kata/budinku.webp", "images/kata/budinku-mob.webp"),
    "bti-cina": ("images/kata/tehnichnyj-pasport.webp", "images/kata/tehnichnyj-pasport-3.webp"),
    "vvedennya-v-ekspluatatsiyu": ("images/kata/vvedennya.webp", "images/kata/vvedennya-mob.webp"),
    "legalizatsiya-neruhomosti": ("images/kata/legalyzacia.webp", "images/kata/legalyzacia-mob.webp"),
    "dozvilna-dokumentatsiya": ("images/kata/dozvilna.webp", "images/kata/dozvilna-mob.webp"),
    "zemelna-dokumentatsiya": ("images/kata/zemelna.webp", "images/kata/zemelna-mob.webp"),
    "dovidky": ("images/kata/dovidky.webp", "images/kata/dovidky-mob.webp"),
    "poslugy-kyiv": ("images/kata/tehnichnyj-pasport.webp", "images/kata/tehnichnyj-pasport-3.webp"),
    "tehnichnyj-pasport-na-kvartyru": ("images/kata/kvartiry.webp", "images/kata/kvartiry-mob.webp"),
    "tehnichnyj-pasport-na-budynok": ("images/kata/budynok.webp", "images/kata/budynok-mob.webp"),
    "elektronnyj-tehnichnyj-pasport": ("images/kata/elektroniy.webp", "images/kata/elektroniy-mob.webp"),
    "tehnichnyj-pasport-na-budivlyu": ("images/kata/budivliu.webp", "images/kata/budivliu-mob.webp"),
    "tehnichnyj-pasport-na-garazh": ("images/kata/garzh.webp", "images/kata/garzh-mob.webp"),
    "tehnichnyj-pasport-na-nezhytlove-prymischennya": (
        "images/kata/nezhitlove.webp",
        "images/kata/nezhitlove-mob.webp",
    ),
    "tehnichnyj-pasport-na-bagato-kvartyrnyj-budynok": (
        "images/kata/bagatokvarirniy.webp",
        "images/kata/bagatokvarirniy-mob.webp",
    ),
    "tehnichna-inventaryzatsiya": ("images/kata/inventaryzacia.webp", "images/kata/inventaryzacia-mob.webp"),
    "kadastrovyj-nomer": ("images/kata/kadasrtoviy.webp", "images/kata/kadasrtoviy-mob.webp"),
    "vytiah-dzk": ("images/kata/vytiahdzk.webp", "images/kata/vytiahdzk-mob.webp"),
    "vysnovky-bti": ("images/kata/vysnovki.webp", "images/kata/vysnovki-mob.webp"),
    "kyiv-oblast": ("images/kata/tehnichnyj-pasport.webp", "images/kata/tehnichnyj-pasport-3.webp"),
}

MANUAL_IMAGES: list[dict] = [
    {
        "page_slug": "global",
        "image_key": "garanty.badge",
        "label": "Бейдж 100% гарантія",
        "fallback_static": "images/kata/100.webp",
        "image_alt_ua": "100% гарантія",
        "image_alt_ru": "100% гарантия",
    },
    {
        "page_slug": "about",
        "image_key": "bg.page",
        "label": "About: фон сторінки",
        "fallback_static": "images/kata/fon.jpeg",
    },
    {
        "page_slug": "about",
        "image_key": "why.photo",
        "label": "About: фото команда",
        "fallback_static": "images/kata/about1.jpeg",
        "image_alt_ua": "Про Метріум",
        "image_alt_ru": "О Метриум",
    },
    {
        "page_slug": "about",
        "image_key": "qual.garant",
        "label": "About: гарантія",
        "fallback_static": "images/kata/garant.png",
        "image_alt_ua": "Гарантія якості",
        "image_alt_ru": "Гарантия качества",
    },
    {
        "page_slug": "home",
        "image_key": "about.passport",
        "label": "Головна: фото паспорта",
        "fallback_static": "images/kata/Vidnovlennya.jpg",
        "image_alt_ua": "Технічний паспорт БТІ",
        "image_alt_ru": "Технический паспорт БТИ",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.marquee.1",
        "label": "Галерея marquee 1",
        "fallback_static": "images/kata/foto1.webp",
        "sort_order": 1,
        "image_alt_ua": "Фото роботи БТІ Метріум",
        "image_alt_ru": "Фото работы БТИ Метриум",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.marquee.2",
        "label": "Галерея marquee 2",
        "fallback_static": "images/kata/foto2.webp",
        "sort_order": 2,
        "image_alt_ua": "Фото роботи БТІ Метріум",
        "image_alt_ru": "Фото работы БТИ Метриум",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.marquee.3",
        "label": "Галерея marquee 3",
        "fallback_static": "images/kata/foto3.webp",
        "sort_order": 3,
        "image_alt_ua": "Фото роботи БТІ Метріум",
        "image_alt_ru": "Фото работы БТИ Метриум",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.marquee.4",
        "label": "Галерея marquee 4",
        "fallback_static": "images/kata/foto4.webp",
        "sort_order": 4,
        "image_alt_ua": "Фото роботи БТІ Метріум",
        "image_alt_ru": "Фото работы БТИ Метриум",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.marquee.5",
        "label": "Галерея marquee 5",
        "fallback_static": "images/kata/foto5.webp",
        "sort_order": 5,
        "image_alt_ua": "Фото роботи БТІ Метріум",
        "image_alt_ru": "Фото работы БТИ Метриум",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.portfolio.1",
        "label": "Портфоліо 1",
        "fallback_static": "images/kata/Tehpasport-na-kvartyru-1.png",
        "sort_order": 11,
        "image_alt_ua": "Зразок технічного паспорта на квартиру",
        "image_alt_ru": "Образец технического паспорта на квартиру",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.portfolio.2",
        "label": "Портфоліо 2",
        "fallback_static": "images/kata/Tehpasport-na-kvartyru-2.png",
        "sort_order": 12,
        "image_alt_ua": "Зразок технічного паспорта на квартиру",
        "image_alt_ru": "Образец технического паспорта на квартиру",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.portfolio.3",
        "label": "Портфоліо 3",
        "fallback_static": "images/kata/Tehpasport-na-budynok-1.png",
        "sort_order": 13,
        "image_alt_ua": "Зразок технічного паспорта на будинок",
        "image_alt_ru": "Образец технического паспорта на дом",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.portfolio.4",
        "label": "Портфоліо 4",
        "fallback_static": "images/kata/Tehpasport-na-budynok-2.png",
        "sort_order": 14,
        "image_alt_ua": "Зразок технічного паспорта на будинок",
        "image_alt_ru": "Образец технического паспорта на дом",
    },
    {
        "page_slug": "global",
        "image_key": "gallery.portfolio.5",
        "label": "Портфоліо 5",
        "fallback_static": "images/kata/Tehpasport-na-budynok-3.png",
        "sort_order": 15,
        "image_alt_ua": "Зразок технічного паспорта на будинок",
        "image_alt_ru": "Образец технического паспорта на дом",
    },
]

DOC_EXAMPLE_IMAGES: dict[str, tuple[str, str, str]] = {
    "tehnichnyj-pasport-na-kvartyru": (
        "images/kata/pasport-kvartyra-zrazok.webp",
        "Зразок технічного паспорта на квартиру",
        "Образец технического паспорта на квартиру",
    ),
    "tehnichnyj-pasport-na-budynok": (
        "images/kata/pasport-budynok-zrazok.webp",
        "Зразок технічного паспорта на будинок",
        "Образец технического паспорта на дом",
    ),
    "tehnichnyj-pasport-na-budivlyu": (
        "images/kata/pasport-budynok-zrazok.webp",
        "Зразок технічного паспорта на будівлю",
        "Образец технического паспорта на здание",
    ),
    "tehnichnyj-pasport-na-garazh": (
        "images/kata/pasport-garazh-zrazok.webp",
        "Зразок технічного паспорта на гараж",
        "Образец технического паспорта на гараж",
    ),
    "tehnichnyj-pasport-na-nezhytlove-prymischennya": (
        "images/kata/pasport-nezhitlova-zrazok.webp",
        "Зразок технічного паспорта на нежитлове приміщення",
        "Образец технического паспорта на нежилое помещение",
    ),
    "tehnichnyj-pasport-na-bagato-kvartyrnyj-budynok": (
        "images/kata/pasport-bagatokvartirny-zrazok.webp",
        "Зразок технічного паспорта на багатоквартирний будинок",
        "Образец технического паспорта на многоквартирный дом",
    ),
    "elektronnyj-tehnichnyj-pasport": (
        "images/kata/pasport-kvartyra-zrazok.webp",
        "Зразок електронного технічного паспорта",
        "Образец электронного технического паспорта",
    ),
    "dovidky": (
        "images/kata/dovidka-zrazok.webp",
        "Зразок довідки БТІ",
        "Образец справки БТИ",
    ),
    "vytiah-dzk": (
        "images/kata/vytiah-zrazok.webp",
        "Зразок витягу з ДЗК",
        "Образец выписки из ГЗК",
    ),
}
