# Generated by Django 5.2.1 on 2026-07-17 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsubmission',
            name='channel',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
