# Generated by Django 5.2.1 on 2026-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Ім'я")),
                ('text', models.TextField(verbose_name='Текст відгуку')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=5, verbose_name='Рейтинг')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опублікований')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Показувати на головній (слайдер)')),
                ('source', models.CharField(choices=[('google', 'Google'), ('site', 'Сайт'), ('other', 'Інше')], default='site', max_length=30, verbose_name='Джерело')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='Дата відгуку')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
