# Generated by Django 5.2.1 on 2026-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('language', models.CharField(choices=[('ua', 'Українська'), ('ru', 'Русский')], default='ua', max_length=5)),
                ('translation_group_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('featured_image', models.ImageField(blank=True, upload_to='blog/')),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'language'), name='unique_blog_slug_per_language')],
            },
        ),
    ]
