# Generated by Django 5.2.1 on 2026-06-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('seo_title', models.CharField(blank=True, max_length=500)),
                ('seo_description', models.TextField(blank=True)),
                ('keywords', models.CharField(blank=True, max_length=500)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('robots_noindex', models.BooleanField(default=False)),
                ('robots_nofollow', models.BooleanField(default=False)),
                ('og_title', models.CharField(blank=True, max_length=500)),
                ('og_description', models.TextField(blank=True)),
                ('og_image_url', models.URLField(blank=True, max_length=500)),
                ('twitter_title', models.CharField(blank=True, max_length=500)),
                ('twitter_description', models.TextField(blank=True)),
                ('schema_json', models.TextField(blank=True)),
                ('sitemap_priority', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('sitemap_changefreq', models.CharField(blank=True, max_length=20)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('content_type', 'object_id'), name='unique_seo_per_object')],
            },
        ),
    ]
