# Generated by Django 5.2.1 on 2026-06-08 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticpage',
            name='is_home',
            field=models.BooleanField(default=False),
        ),
    ]
