# Generated by Django 5.2.1 on 2026-06-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_path', models.CharField(db_index=True, max_length=500, unique=True)),
                ('target_url', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('htaccess', 'htaccess 410'), ('eps', 'EPS 301'), ('manual', 'Manual')], default='manual', max_length=20)),
            ],
            options={
                'ordering': ['source_path'],
            },
        ),
    ]
