# Generated by Django 5.2.1 on 2026-06-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('title', models.CharField(max_length=200, verbose_name='Назва (відображується)')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Адреса')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True, verbose_name='Довгота')),
                ('map_embed_url', models.TextField(blank=True, verbose_name='URL embed карти')),
                ('map_link', models.URLField(blank=True, max_length=500, verbose_name='Google Maps посилання')),
                ('waze_link', models.URLField(blank=True, max_length=500, verbose_name='Waze посилання')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортування')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('is_main', models.BooleanField(default=False, verbose_name='Головний офіс')),
            ],
            options={
                'verbose_name': 'Офіс',
                'verbose_name_plural': 'Офіси',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
