# Generated by Django 5.2.1 on 2026-06-15 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial_office'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Metrium', max_length=100, verbose_name='Назва сайту')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Логотип')),
                ('logo_alt_ua', models.CharField(default='Метріум БТІ', max_length=200, verbose_name='Alt логотипу (UA)')),
                ('logo_alt_ru', models.CharField(default='Метриум БТИ', max_length=200, verbose_name='Alt логотипу (RU)')),
                ('schedule_header_ua', models.CharField(default='Пн-Пт: 08:00–21:00 | Сб: 09:00–18:00', max_length=200, verbose_name='Графік у шапці (UA)')),
                ('schedule_header_ru', models.CharField(default='Пн-Пт: 08:00–21:00 | Сб: 09:00–18:00', max_length=200, verbose_name='Графік у шапці (RU)')),
                ('schedule_weekdays_ua', models.CharField(default='Пн-Пт: 08:00 – 21:00', max_length=100, verbose_name='Пн-Пт (UA)')),
                ('schedule_weekdays_ru', models.CharField(default='Пн-Пт: 08:00 – 21:00', max_length=100, verbose_name='Пн-Пт (RU)')),
                ('schedule_saturday_ua', models.CharField(default='Сб: 09:00 – 18:00', max_length=100, verbose_name='Субота (UA)')),
                ('schedule_saturday_ru', models.CharField(default='Сб: 09:00 – 18:00', max_length=100, verbose_name='Субота (RU)')),
                ('schedule_sunday_ua', models.CharField(default='Нд: Вихідний', max_length=100, verbose_name='Неділя (UA)')),
                ('schedule_sunday_ru', models.CharField(default='Вс: Выходной', max_length=100, verbose_name='Неділя (RU)')),
                ('email', models.EmailField(default='pruvatnebti@gmail.com', max_length=254, verbose_name='Email')),
                ('region_label_ua', models.CharField(default='м. Київ та Київська область', max_length=200, verbose_name='Регіон (UA)')),
                ('region_label_ru', models.CharField(default='г. Киев и Киевская область', max_length=200, verbose_name='Регіон (RU)')),
                ('telegram', models.URLField(blank=True, default='https://t.me/metriumbti', verbose_name='Telegram')),
                ('viber', models.CharField(blank=True, default='viber://chat?number=%2B380673986200', max_length=300, verbose_name='Viber')),
                ('whatsapp', models.URLField(blank=True, default='https://wa.me/380673986200', verbose_name='WhatsApp')),
                ('instagram', models.URLField(blank=True, default='https://www.instagram.com/pruvatnebti', verbose_name='Instagram')),
                ('facebook', models.URLField(blank=True, default='https://www.facebook.com/profile.php?id=61584165429803', verbose_name='Facebook')),
                ('footer_consult_title_ua', models.CharField(default='Отримати консультацію зараз', max_length=200, verbose_name='Футер: заголовок форми (UA)')),
                ('footer_consult_title_ru', models.CharField(default='Получить консультацию сейчас', max_length=200, verbose_name='Футер: заголовок форми (RU)')),
                ('footer_rights_ua', models.CharField(default='Всі права захищено.', max_length=200, verbose_name='Футер: права (UA)')),
                ('footer_rights_ru', models.CharField(default='Все права защищены.', max_length=200, verbose_name='Футер: права (RU)')),
                ('privacy_url', models.CharField(blank=True, default='#', max_length=300, verbose_name='Посилання політики')),
                ('privacy_label_ua', models.CharField(default='Політика конфіденційності', max_length=100, verbose_name='Політика конфіденційності (UA)')),
                ('privacy_label_ru', models.CharField(default='Политика конфиденциальности', max_length=100, verbose_name='Політика конфіденційності (RU)')),
                ('hero_image_desktop', models.ImageField(blank=True, help_text='Рекомендовано 1920×800 px', upload_to='hero/', verbose_name='Hero: фото (десктоп)')),
                ('hero_image_mobile', models.ImageField(blank=True, help_text='Рекомендовано 768×900 px', upload_to='hero/', verbose_name='Hero: фото (мобільний)')),
                ('hero_title_ua', models.TextField(default='Бюро Технічної\nІнвентаризації', verbose_name='Hero: заголовок (UA)')),
                ('hero_title_ru', models.TextField(default='Бюро Технической\nИнвентаризации', verbose_name='Hero: заголовок (RU)')),
                ('hero_subtitle_ua', models.TextField(default='Послуги БТІ без прихованих платежів!\nШвидко, зручно, надійно!', verbose_name='Hero: підзаголовок (UA)')),
                ('hero_subtitle_ru', models.TextField(default='Услуги БТИ без скрытых платежей!\nБыстро, удобно, надежно!', verbose_name='Hero: підзаголовок (RU)')),
                ('hero_form_title_ua', models.CharField(default='Швидке замовлення технічного паспорта БТІ', max_length=300, verbose_name='Hero: заголовок форми (UA)')),
                ('hero_form_title_ru', models.CharField(default='Быстрый заказ технического паспорта БТИ', max_length=300, verbose_name='Hero: заголовок форми (RU)')),
                ('hero_form_text_ua', models.TextField(default="Для замовлення залиште Ваш номер телефону і наша команда спеціалістів з Вами зв'яжеться", verbose_name='Hero: текст форми (UA)')),
                ('hero_form_text_ru', models.TextField(default='Для заказа оставьте Ваш номер телефона и наша команда специалистов с Вами свяжется', verbose_name='Hero: текст форми (RU)')),
            ],
            options={
                'verbose_name': 'Налаштування сайту',
                'verbose_name_plural': 'Налаштування сайту',
            },
        ),
        migrations.CreateModel(
            name='SitePhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel_href', models.CharField(default='tel:0673986200', max_length=30, verbose_name='Посилання tel:')),
                ('display', models.CharField(default='067-398-62-00', max_length=30, verbose_name='Відображення')),
                ('sort_order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='core.sitesettings', verbose_name='Налаштування')),
            ],
            options={
                'verbose_name': 'Телефон',
                'verbose_name_plural': 'Телефони',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
