# Generated by Django 5.2.15 on 2026-07-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_sitephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram',
            field=models.URLField(blank=True, default='https://telegram.me/metriumbti', verbose_name='Telegram'),
        ),
    ]
