# Generated by Django 5.2.1 on 2026-06-08 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('banner', 'Банер'), ('text', 'Текст'), ('calculator', 'Калькулятор'), ('services', 'Послуги'), ('price_list', 'Прайс'), ('lead_form', 'Форма заявки'), ('faq', 'FAQ'), ('reviews', 'Відгуки'), ('seo_text', 'SEO текст'), ('map', 'Карта'), ('video', 'Відео'), ('gallery', 'Галерея'), ('steps', 'Кроки'), ('brands', 'Бренди'), ('html', 'HTML (legacy)')], max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('css_anchor', models.SlugField(blank=True, max_length=100)),
                ('heading', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='blocks/')),
                ('image_alt', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, max_length=200)),
                ('button_url', models.CharField(blank=True, max_length=500)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
