# Generated by Django 5.2.1 on 2026-06-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_add_contacts_main_links_garanty_kinds'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeServiceCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=300, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=300, verbose_name='Заголовок (RU)')),
                ('description_ua', models.TextField(blank=True, verbose_name='Опис (UA)')),
                ('description_ru', models.TextField(blank=True, verbose_name='Опис (RU)')),
                ('icon', models.ImageField(blank=True, upload_to='home/services/', verbose_name='Іконка')),
                ('url', models.CharField(max_length=300, verbose_name='Посилання')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Картка послуги (головна)',
                'verbose_name_plural': 'Картки послуг (головна)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeStatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='Цифра')),
                ('label_ua', models.CharField(max_length=200, verbose_name='Підпис (UA)')),
                ('label_ru', models.CharField(max_length=200, verbose_name='Підпис (RU)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Статистика (головна)',
                'verbose_name_plural': 'Статистика (головна)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeWhyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Заголовок (UA)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Заголовок (RU)')),
                ('text_ua', models.TextField(verbose_name='Текст (UA)')),
                ('text_ru', models.TextField(verbose_name='Текст (RU)')),
                ('icon', models.ImageField(blank=True, upload_to='home/why/', verbose_name='Іконка')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Перевага (головна)',
                'verbose_name_plural': 'Переваги (головна)',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(choices=[('global', 'Загальне'), ('home', 'Головна'), ('header', 'Шапка'), ('footer', 'Футер'), ('about', 'Про нас'), ('contacts', 'Контакти'), ('blog', 'Блог'), ('reviews', 'Відгуки'), ('tehnichni-pasporty-bti', 'Технічні паспорти'), ('bti-cina', 'Ціна БТІ'), ('vvedennya-v-ekspluatatsiyu', 'Введення в експлуатацію'), ('legalizatsiya-neruhomosti', 'Легалізація'), ('dozvilna-dokumentatsiya', 'Дозвільна документація'), ('zemelna-dokumentatsiya', 'Земельна документація'), ('dovidky', 'Довідки'), ('poslugy-kyiv', 'Послуги Київ'), ('neobhidni-dokumenty', 'Необхідні документи'), ('tehnichnyj-pasport-na-kvartyru', 'Паспорт на квартиру'), ('tehnichnyj-pasport-na-budynok', 'Паспорт на будинок'), ('elektronnyj-tehnichnyj-pasport', 'Електронний паспорт'), ('tehnichnyj-pasport-na-budivlyu', 'Паспорт на будівлю'), ('tehnichnyj-pasport-na-garazh', 'Паспорт на гараж'), ('tehnichnyj-pasport-na-nezhytlove-prymischennya', 'Нежитлове приміщення'), ('tehnichnyj-pasport-na-bagato-kvartyrnyj-budynok', 'Багатоквартирний будинок'), ('tehnichna-inventaryzatsiya', 'Інвентаризація'), ('kadastrovyj-nomer', 'Кадастровий номер'), ('vytiah-dzk', 'Витяг ДЗК'), ('vysnovky-bti', 'Висновки БТІ'), ('kyiv-oblast', 'Київська область')], max_length=100, verbose_name='Сторінка')),
                ('section_key', models.SlugField(max_length=100, verbose_name='Ключ секції')),
                ('label', models.CharField(max_length=200, verbose_name='Назва в адмінці')),
                ('text_ua', models.TextField(blank=True, verbose_name='Текст (UA)')),
                ('text_ru', models.TextField(blank=True, verbose_name='Текст (RU)')),
                ('body_ua', models.TextField(blank=True, verbose_name='HTML / довгий текст (UA)')),
                ('body_ru', models.TextField(blank=True, verbose_name='HTML / довгий текст (RU)')),
                ('image', models.ImageField(blank=True, upload_to='sections/', verbose_name='Зображення')),
                ('image_alt_ua', models.CharField(blank=True, max_length=255, verbose_name='Alt зображення (UA)')),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt зображення (RU)')),
                ('icon', models.ImageField(blank=True, upload_to='sections/icons/', verbose_name='Іконка')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='Посилання')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Секція сторінки',
                'verbose_name_plural': 'Секції сторінок',
                'ordering': ['page_slug', 'sort_order', 'section_key'],
                'constraints': [models.UniqueConstraint(fields=('page_slug', 'section_key'), name='unique_page_section_key')],
            },
        ),
    ]
