# Generated by Django 5.1.15 on 2026-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_homeservicecard_homestatitem_homewhyitem_pagesection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagesection',
            options={'ordering': ['page_slug', 'sort_order', 'section_key'], 'verbose_name': 'Текст сторінки', 'verbose_name_plural': 'Тексти сторінок'},
        ),
        migrations.CreateModel(
            name='SiteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_slug', models.CharField(choices=[('global', 'Загальне'), ('home', 'Головна'), ('header', 'Шапка'), ('footer', 'Футер'), ('about', 'Про нас'), ('contacts', 'Контакти'), ('blog', 'Блог'), ('reviews', 'Відгуки'), ('tehnichni-pasporty-bti', 'Технічні паспорти'), ('bti-cina', 'Ціна БТІ'), ('vvedennya-v-ekspluatatsiyu', 'Введення в експлуатацію'), ('legalizatsiya-neruhomosti', 'Легалізація'), ('dozvilna-dokumentatsiya', 'Дозвільна документація'), ('zemelna-dokumentatsiya', 'Земельна документація'), ('dovidky', 'Довідки'), ('poslugy-kyiv', 'Послуги Київ'), ('neobhidni-dokumenty', 'Необхідні документи'), ('tehnichnyj-pasport-na-kvartyru', 'Паспорт на квартиру'), ('tehnichnyj-pasport-na-budynok', 'Паспорт на будинок'), ('elektronnyj-tehnichnyj-pasport', 'Електронний паспорт'), ('tehnichnyj-pasport-na-budivlyu', 'Паспорт на будівлю'), ('tehnichnyj-pasport-na-garazh', 'Паспорт на гараж'), ('tehnichnyj-pasport-na-nezhytlove-prymischennya', 'Нежитлове приміщення'), ('tehnichnyj-pasport-na-bagato-kvartyrnyj-budynok', 'Багатоквартирний будинок'), ('tehnichna-inventaryzatsiya', 'Інвентаризація'), ('kadastrovyj-nomer', 'Кадастровий номер'), ('vytiah-dzk', 'Витяг ДЗК'), ('vysnovky-bti', 'Висновки БТІ'), ('kyiv-oblast', 'Київська область')], max_length=100, verbose_name='Сторінка')),
                ('image_key', models.SlugField(max_length=100, verbose_name='Ключ зображення')),
                ('label', models.CharField(max_length=200, verbose_name='Назва в адмінці')),
                ('image', models.ImageField(blank=True, upload_to='site-images/', verbose_name='Зображення')),
                ('image_mobile', models.ImageField(blank=True, upload_to='site-images/', verbose_name='Зображення (мобільне)')),
                ('image_alt_ua', models.CharField(blank=True, max_length=255, verbose_name='Alt (UA)')),
                ('image_alt_ru', models.CharField(blank=True, max_length=255, verbose_name='Alt (RU)')),
                ('fallback_static', models.CharField(blank=True, help_text='Шлях від static/, напр. images/kata/kvartiry.webp', max_length=300, verbose_name='Fallback static (desktop)')),
                ('fallback_static_mobile', models.CharField(blank=True, max_length=300, verbose_name='Fallback static (mobile)')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активне')),
            ],
            options={
                'verbose_name': 'Зображення сайту',
                'verbose_name_plural': 'Зображення сайту',
                'ordering': ['page_slug', 'sort_order', 'image_key'],
                'constraints': [models.UniqueConstraint(fields=('page_slug', 'image_key'), name='unique_site_image_key')],
            },
        ),
    ]
