# Generated by Django 5.2.1 on 2026-07-17 07:45

import django.db.models.deletion
from django.db import migrations, models


def link_existing_sections_and_images(apps, schema_editor):
    """Прив'язує вже наявні PageSection/SiteImage до відповідної StaticPage за slug.

    Для кожного унікального page_slug шукаємо StaticPage з таким же slug
    (перевага — українській версії), і, якщо знайдено, прив'язуємо через
    content_type/object_id. Записи без відповідної сторінки (шапка, футер,
    загальні тексти тощо) лишаються без прив'язки — це очікувано.
    """
    ContentType = apps.get_model("contenttypes", "ContentType")
    StaticPage = apps.get_model("pages", "StaticPage")
    PageSection = apps.get_model("cms", "PageSection")
    SiteImage = apps.get_model("cms", "SiteImage")

    content_type = ContentType.objects.get_for_model(StaticPage)

    home_anchor = StaticPage.objects.filter(is_home=True, language="ua").first() or StaticPage.objects.filter(
        is_home=True
    ).first()

    slugs = set(PageSection.objects.values_list("page_slug", flat=True)) | set(
        SiteImage.objects.values_list("page_slug", flat=True)
    )
    for slug in slugs:
        if slug == "home":
            anchor = home_anchor
        else:
            anchor = StaticPage.objects.filter(slug=slug, language="ua").first() or StaticPage.objects.filter(
                slug=slug
            ).order_by("language").first()
        if not anchor:
            continue
        PageSection.objects.filter(page_slug=slug, content_type__isnull=True).update(
            content_type=content_type, object_id=anchor.pk
        )
        SiteImage.objects.filter(page_slug=slug, content_type__isnull=True).update(
            content_type=content_type, object_id=anchor.pk
        )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_siteimage'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('pages', '0002_staticpage_is_home'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='pagesection',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='content_type',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='siteimage',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='pagesection',
            index=models.Index(fields=['content_type', 'object_id'], name='cms_pagesec_content_6b27dc_idx'),
        ),
        migrations.AddIndex(
            model_name='siteimage',
            index=models.Index(fields=['content_type', 'object_id'], name='cms_siteima_content_599a37_idx'),
        ),
        migrations.RunPython(link_existing_sections_and_images, noop),
    ]
