# Generated by Django 5.2.15 on 2026-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_fix_home_service_card_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagesection',
            name='block_title',
            field=models.CharField(blank=True, db_index=True, help_text='Група полів як на сторінці: Hero, Основний опис, FAQ…', max_length=200, verbose_name='Блок на сайті'),
        ),
        migrations.AlterField(
            model_name='pagesection',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показувати на сайті'),
        ),
    ]
